FROM node:18-alpine AS build

WORKDIR /app

# Copy package files and install dependenciesAdd commentMore actions
COPY package*.json ./

# Install dependencies inside image
RUN npm install

# Copy rest of the source code
COPY . .

# Build the Vite app
RUN npm run build


FROM nginx:alpine


# Set working directory where Nginx serves files
WORKDIR /usr/share/nginx/html

RUN chmod -R a+rx .

# Copy built static files from previous stage
COPY --from=build /app/dist .

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]