services:
  mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    working_dir: /frontend
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    working_dir: /backend
    command: npm run dev

volumes:
  frontend_node_modules:
